### ISSUE TITLE
Potential change to code generation strategy

### ISSUE THREAD

**Issue by thorulf4** [Ecdar/Ecdar-ProtoBuf#1]
### How it works now
From my current understanding we manually generate java, kotlin and eventually rust code and save it in this repo whenever we want to change the protobuf files.
When we want to use the protobuf we would then manually copy these generated files over to the their respective projects.

### My recommendation
We remove all generated code from this repo so it only contains protobuf files and a readme file.
Then for projects that depend on this these protobuf definitions would include this repo as a submodule, allowing us to change the protobuf files separately from all the projects.
Code generation could then be automated by as a part of the build process, this seems to be the preferred way to handle generating code from protobuf files.

Tools already exist for generating protobuf files during compilation.
- Gradle integration: https://github.com/google/protobuf-gradle-plugin
- Cargo integration: https://github.com/hyperium/tonic/tree/master/tonic-build

Expected github structure would be:

```
master
  - component.proto
  - objects.proto
  - query.proto
  - README.md
```

### Benefits of this approach
There might be some negatives with git submodules im not aware of, but they seem like a solid solution to me.

- We dont have to manually copy the generated files ever
- It makes updating the protobuf simpler, and it just focuses on definitions and not generation details
- Future projects would be easier to add as we dont need to add another generation on this repo

**Comment by Nielswps** [comment]
I think this proposed change is the ideal way to handle the ProtoBuf dependencies across the ecosystem :ok_hand:
Assuming that Ulrik and the others agree, I can start implementing the Gradle plugin into the GUI quite soon :smile:
